
const INCREMENT_COUNT = 'INCREMENT_COUNT';
const DECREMENT_COUNT = 'DECREMENT_COUNT';

const SHOW_PLAYER_ENTRY_MODAL = 'SHOW_PLAYER_ENTRY_MODAL';
const HIDE_PLAYER_ENTRY_MODAL = 'HIDE_PLAYER_ENTRY_MODAL';

export { INCREMENT_COUNT, DECREMENT_COUNT, SHOW_PLAYER_ENTRY_MODAL, HIDE_PLAYER_ENTRY_MODAL }; 